AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name

  LogLevel:
    Type: String
    Default: INFO
  
  FlightTable:
    Type: String
    Description: Flight Table

Globals:
  Function:
    Runtime: python3.9
    Architectures:
      - arm64
    Handler: main.handler
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: !Ref LogLevel
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension-Arm64:1"

Resources:
  ReserveFlight:
    Type: AWS::Serverless::Function
    Properties:
      Handler: reserve.lambda_handler
      CodeUri: src/reserve-flight
      Timeout: 10
      Environment:
        Variables:
          FLIGHT_TABLE_NAME: !Ref FlightTable
      Policies:
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:*
              Resource: '*'

  ReleaseFlight:
    Type: AWS::Serverless::Function
    Properties:
      Handler: release.lambda_handler
      CodeUri: src/release-flight
      Timeout: 10
      Environment:
        Variables:
          FLIGHT_TABLE_NAME: !Ref FlightTable
      Policies:
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:*
              Resource: '*'

  ReserveFlightParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${Environment}/service/catalog/reserveFunction
      Description: Reserve Flight Lambda ARN
      Type: String
      Value: !Sub ${ReserveFlight.Arn}

  ReleaseFlightParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${Environment}/service/catalog/releaseFunction
      Description: Release Flight Lambda ARN
      Type: String
      Value: !Sub ${ReleaseFlight.Arn}

Outputs:
  ReserveFlightFunction:
    Value: !Sub ${ReserveFlight.Arn}
    Description: Reserve Flight Lambda Function

  ReleaseFlightFunction:
    Value: !Sub ${ReleaseFlight.Arn}
    Description: Release Flight Lambda Function